### PR TITLE
Adds the release name (target update version)

### PR DESCRIPTION
**Pull request by fraga**
Following new updated json file that adds the target update version to the upcoming calendar view model

### CODE REVIEW

**Comment by FH-Inway** [comment]
Awesome, thank you!

Would be nice to add it to the "Upcoming Updates" form as well. Let me know if you want to work on that and if you want to do it in this pr.

image

image

**Comment by fraga** [comment]
@FH-Inway sure ! I never actually navigated to that form I just always exported it. Any suggestions for the name? Release name seems just too long:
Release Name
image

Version
image

**Comment by FH-Inway** [comment]
> Any suggestions for the name? Release name seems just too long:

I'm good with either option. Would prefer Release name, just because it maps to what is displayed in LCS and the name of the data object. I get the "too long" argument, but since we already have several other columns where the header is longer than one line, I don't think it really matters. Your choice :) 

Thanks for taking on the additional work. ❤️

**Comment by fraga** [comment]
There you go the designer on VS 2022 changed a lot, let me know if you need me to fix anything before merging.

**Comment by FH-Inway** [comment]
Thanks again, new version [0.50.0](https://github.com/microsoft/2LCS/releases/tag/v.0.50.0) is released.

**Pull request merged**
